version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily" 
    open-pull-requests-limit: 10
    reviewers:
      - "0xEbrahim" 
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
