version: "3.8"
services:
  db:
    container_name: db
    image: cockroachdb/cockroach:latest
    ports:
      - published: 26257
        target: 26257
      - published: 8080
        target: 8080
    volumes:
      - ./cockroach-data:/cockroachdb/cockroach-data
    command: start-single-node --insecure
  web:
    build: .
    depends_on:
      - db
    container_name: web
    ports:
      - published: 3000
        target: 3000
    env_file:
      - .env
    volumes:
      - .:/backend
      - /backend/node_modules
    working_dir: /backend

volumes:
  cockroach-data:
