openapi: 3.0.0
info:
  title: LMS API
  description: Docs for LMS API
  version: 1.0.0
servers:
  - url: /api/v1
    description: Base API URL
tags:
  - name: Auth
    description: Authentication and authorization endpoints
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      description: Register a new user with the provided details
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  example: john.doe@example.com
                password:
                  type: string
                  example: password123
                confirmPassword:
                  type: string
                  example: password123
                image:
                  type: string
                  format: binary
                  description: User's avatar image
      responses:
        "201":
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Success
                  message:
                    type: string
                    example: Account created successfully, please check your Gmail account to verify your email
        "409":
          description: Email already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Error
                  message:
                    type: string
                    example: Email is already exists, try another email.
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Error
                  message:
                    type: string
                    example: Error while creating account, please try again

  /auth/login:
    post:
      tags:
        - Auth
      summary: Login a user
      description: Login a user with the provided credentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginBody"
      responses:
        "200":
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Success
                  data:
                    type: object
                    properties:
                      user:
                        $ref: "#/components/schemas/User"
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  refreshToken:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        "401":
          description: Incorrect email or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Error
                  message:
                    type: string
                    example: Incorrect email or password.
        "403":
          description: Email not verified
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Error
                  message:
                    type: string
                    example: Your email is not verified, please check your email to verify it.

  /auth/logout:
    post:
      tags:
        - Auth
      summary: Logout a user
      description: Logout a user by invalidating the token
      security:
        - BearerAuth: []
      responses:
        "200":
          description: User logged out successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Success
                  message:
                    type: string
                    example: You have been logged out successfully.
        "403":
          description: Invalid or expired token
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Error
                  message:
                    type: string
                    example: Expired session, please login again

  /auth/refresh:
    get:
      tags:
        - Auth
      summary: Refresh access token
      description: Refresh the access token using the refresh token
      responses:
        "200":
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Success
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        "403":
          description: Expired session or invalid token
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Error
                  message:
                    type: string
                    example: Expired session, please login again

  /auth/verify-Email/{token}:
    get:
      tags:
        - Auth
      summary: Verify email
      description: Verify the user's email using the verification token
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
          description: Email verification token
      responses:
        "200":
          description: Email verified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Success
                  message:
                    type: string
                    example: Email verified, now you can login to your account.
        "403":
          description: Invalid or expired token
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Error
                  message:
                    type: string
                    example: Invalid or expired token
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Error
                  message:
                    type: string
                    example: Error while verifying user's email

  /auth/google:
    get:
      tags:
        - Auth
      summary: Google OAuth
      description: Authenticate using Google OAuth
      responses:
        "302":
          description: Redirect to Google OAuth page

  /auth/google/callback:
    get:
      tags:
        - Auth
      summary: Google OAuth callback
      description: Callback URL for Google OAuth
      responses:
        "200":
          description: User authenticated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Success
                  data:
                    type: object
                    properties:
                      user:
                        $ref: "#/components/schemas/User"
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        "302":
          description: Redirect to login page on failure

  /auth/forgot-password:
    patch:
      tags:
        - Auth
      summary: Forgot password
      description: Request a password reset link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ForgotPasswordBody"
      responses:
        "200":
          description: Password reset link sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Success
                  message:
                    type: string
                    example: Please check your email for reset password link
        "404":
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Error
                  message:
                    type: string
                    example: Invalid email, cannot find user.

  /auth/reset-password:
    post:
      tags:
        - Auth
      summary: Reset password
      description: Reset the user's password using the reset token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResetPasswordBody"
      responses:
        "200":
          description: Password reset successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Success
                  message:
                    type: string
                    example: Password reset successfully, try login with the new password
        "403":
          description: Invalid or expired token
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Error
                  message:
                    type: string
                    example: Invalid or expired token

  /auth/send-email:
    patch:
      tags:
        - Auth
      summary: Send email verification token
      description: Send an email verification token to the user's email
      responses:
        "200":
          description: Email sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Success
                  message:
                    type: string
                    example: Email sent successfully, please check your Gmail account to verify your email
        "403":
          description: User not allowed to use this endpoint
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Error
                  message:
                    type: string
                    example: You are not allowed to use this endpoint

components:
  schemas:
    RegisterBody:
      type: object
      properties:
        name:
          type: string
          example: John Doe
        email:
          type: string
          example: john.doe@example.com
        password:
          type: string
          example: password123
        confirmPassword:
          type: string
          example: password123
        avatar:
          type: string
          format: binary
          example: "path/to/avatar.jpg"

    LoginBody:
      type: object
      properties:
        email:
          type: string
          example: john.doe@example.com
        password:
          type: string
          example: password123

    ForgotPasswordBody:
      type: object
      properties:
        email:
          type: string
          example: john.doe@example.com

    ResetPasswordBody:
      type: object
      properties:
        token:
          type: string
          example: "reset-token"
        password:
          type: string
          example: newpassword123
        confirmPassword:
          type: string
          example: newpassword123

    User:
      type: object
      properties:
        id:
          type: string
          example: "12345"
        name:
          type: string
          example: John Doe
        email:
          type: string
          example: john.doe@example.com
        avatar:
          type: string
          example: "https://example.com/avatar.jpg"
        emailVerified:
          type: boolean
          example: true
        isActive:
          type: boolean
          example: true

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
