export default {
  NODE_ENV: process.env.NODE_ENV,
  PORT: parseInt(process.env.PORT as string) as Number,
  DEV_URL: process.env.DEV_URL as string,
  PROD_URL: process.env.PROD_URL as string,
  DB_PASS: process.env.DB_PASS,
  DATABASE_URL: process.env.DATABASE_URL,
  LOGS_TOKEN: process.env.LOGS_TOKEN as string,
  LOGS_HOST: process.env.LOGS_HOST,
  JWT_SECRET: process.env.JWT_SECRET,
  JWT_EXPIRES_IN: parseInt(process.env.JWT_EXPIRES_IN as string),
  REFRESH_SECRET: process.env.REFRESH_SECRET,
  REFRESH_EXPIRES_IN: parseInt(process.env.REFRESH_EXPIRES_IN as string),
  CLOUD_NAME: process.env.CLOUD_NAME as string,
  CLOUD_KEY: process.env.CLOUD_KEY as string,
  CLOUD_SECRET: process.env.CLOUD_SECRET as string,
  CLOUDINARY_URL: process.env.CLOUDINARY_URL as string,
  SMTP_HOST: process.env.SMTP_HOST,
  SMTP_PORT: parseInt(process.env.SMTP_PORT as string),
  SMTP_USER: process.env.SMTP_USER,
  SMTP_PASS: process.env.SMTP_PASS,
  SESSION_SECRET: process.env.SESSION_SECRET as string,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID as string,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET as string,
  GOOGLE_DEV_CALLBACK: process.env.GOOGLE_DEV_CALLBACK as string,
  GOOGLE_PROD_CALLBACK: process.env.GOOGLE_PROD_CALLBACK as string,
};
